name: Apptainer Build Deploy

on:
  push:
    tags:        
      - '*'           # Push events to every tag not containing /

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: kaczmarj/apptainer:latest
        options: --privileged

    name: Build Container
    steps:

      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Build Container
        run: |
          apptainer build lolcow.sif lolcow.def
          apptainer build fortune.sif fortune.def

      - name: Login and Deploy Container
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u "${{ github.actor }}" --password-stdin oras://ghcr.io
          apptainer push lolcow.sif oras://ghcr.io/${{ github.repository_owner }}/lolcow:${GITHUB_REF_NAME}
          apptainer push fortune.sif oras://ghcr.io/${{ github.repository_owner }}/fortune:${GITHUB_REF_NAME}
